import React, { useState, useEffect } from 'react';
import { Edit2, Image as ImageIcon, Send, CheckCircle2, Loader2, Pencil } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/app/components/ui/card';
import { Button } from '@/app/components/ui/button';
import { Label } from '@/app/components/ui/label';
import { Badge } from '@/app/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/app/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/app/components/ui/dialog';
import { Textarea } from '@/app/components/ui/textarea';
import { ImageUploader } from './content-audit/image-uploader';
import { GeneratedGallery, generateMockImages, GenerationStatus, GeneratedImage } from './content-audit/generated-gallery';
import { SocialPreviewTabs } from './content-audit/social-preview-tabs';
import { cn } from '@/app/components/ui/utils';
import { BobaProgress } from '@/app/components/ui/BobaProgress';
import { useBobaFakeProgress } from '@/app/hooks/useBobaFakeProgress';
import { TeaFlowProgressBar } from '@/app/components/ui/TeaFlowProgressBar';
import { useTeaFlowFakeProgress } from '@/app/hooks/useTeaFlowFakeProgress';

type Stage = 'waiting_input' | 'copy_generating' | 'copy_ready' | 'image_generating' | 'done';

interface CopyStyle {
  id: string;
  name: string;
  icon: string;
  content: string; // AI 產出的原始文案
  editedText?: string; // 使用者編輯後的文案（可選）
}

interface ImageMeta {
  width: number;
  height: number;
  size: number;
}

export function ContentAuditCenter() {
  // Mock products data
  const products = [
    '烤楊奶茶鮮萃紅',
    '青蛙汁',
  ];

  // Stage state machine
  const [stage, setStage] = useState<Stage>('waiting_input');
  
  // Form state
  const [selectedProduct, setSelectedProduct] = useState<string>('');
  
  // Image state
  const [uploadedImage, setUploadedImage] = useState<string | null>(null);
  const [uploadedMeta, setUploadedMeta] = useState<ImageMeta | null>(null);
  
  // Copy candidates state (initially empty, generated by AI)
  const [copyCandidates, setCopyCandidates] = useState<CopyStyle[]>([]);
  const [selectedCopyId, setSelectedCopyId] = useState<string | null>(null);
  
  // Image generation state
  const [generatedImages, setGeneratedImages] = useState<GeneratedImage[]>([]);
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [generationStatus, setGenerationStatus] = useState<GenerationStatus>('idle');
  const [generationProgress, setGenerationProgress] = useState(0);
  
  // Error message state
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Edit dialog state
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [editingCopyId, setEditingCopyId] = useState<string | null>(null);
  const [editTextValue, setEditTextValue] = useState<string>('');

  // Boba progress state (for copy generation)
  const { progress, status, start, finish, reset } = useBobaFakeProgress({ expectedMs: 60000 });
  const [showBobaProgress, setShowBobaProgress] = useState(false);

  // TeaFlow progress state (for image generation)
  const { 
    progress: teaFlowProgress, 
    status: teaFlowStatus, 
    start: teaFlowStart, 
    finish: teaFlowFinish, 
    reset: teaFlowReset 
  } = useTeaFlowFakeProgress({ expectedMs: 60000 });
  const [showTeaFlowProgress, setShowTeaFlowProgress] = useState(false);
  const [selectedStyleName, setSelectedStyleName] = useState<string>('');

  // Reset function: clear copyCandidates, selectedCopyId, imageResult and return to waiting_input
  const resetState = () => {
    setCopyCandidates([]);
    setSelectedCopyId(null);
    setGeneratedImages([]);
    setSelectedImage(null);
    setGenerationStatus('idle');
    setGenerationProgress(0);
    setStage('waiting_input');
    setErrorMessage(null);
    setIsEditDialogOpen(false);
    setEditingCopyId(null);
    setEditTextValue('');
    reset();
    setShowBobaProgress(false);
    teaFlowReset();
    setShowTeaFlowProgress(false);
    setSelectedStyleName('');
  };

  // Handle image upload
  const handleImageUpload = (file: File, preview: string, meta: ImageMeta) => {
    setUploadedImage(preview);
    setUploadedMeta(meta);
    resetState();
  };

  // Handle image clear
  const handleImageClear = () => {
    setUploadedImage(null);
    setUploadedMeta(null);
    resetState();
  };

  // Handle product change
  const handleProductChange = (value: string) => {
    setSelectedProduct(value);
    resetState();
  };

  // Mock generateCopies API call
  const generateCopies = async (productName: string): Promise<CopyStyle[]> => {
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Use default templateId if backend requires it
    // In production API call, you can include: templateId: "product-only" (or other default)
    
    // Mock generated copies based on product
    return [
      {
        id: 'trendy',
        name: '潮流風格',
        icon: '🔥',
        content: `${productName} 絕對是今年冬天最chill的選擇～濃郁烤糖遇上酸甜草莓，每一口都是驚喜💕 限時開賣中，tag你的姊妹一起來打卡！`
      },
      {
        id: 'literary',
        name: '文青風格',
        icon: '📖',
        content: `冬日午後，一杯${productName}。\n\n溫暖的烤糖香氣，包裹著莓果的清新，如同舊時光裡那些美好的片段。\n\n季節限定，與你分享這份冬季的小確幸。`
      },
      {
        id: 'humor',
        name: '幽默風格',
        icon: '😄',
        content: `老闆說：「這杯${productName}賣不好就扣你薪水！」\n我說：「那我先喝三杯壓壓驚。」\n\n結果...我真的連喝三杯 🤣\n#太好喝了吧 #減肥明天再說`
      }
    ];
  };

  // Handle AI copy generation button click (only generates copies, not images)
  const handleGenerateCopiesClick = async () => {
    // Check prerequisites: uploaded image + selected product
    if (!uploadedImage) {
      setErrorMessage('請先上傳產品圖片');
      setTimeout(() => setErrorMessage(null), 3000);
      return;
    }
    
    if (!selectedProduct) {
      setErrorMessage('請先選擇產品名稱');
      setTimeout(() => setErrorMessage(null), 3000);
      return;
    }
    
    // Start copy generation
    setStage('copy_generating');
    setCopyCandidates([]);
    setSelectedCopyId(null);
    setErrorMessage(null);
    
    // Show and start boba progress
    setShowBobaProgress(true);
    start();
    
    // ============================================
    // 🔄 DEMO: 模擬 API 完成（6 秒後自動完成）
    // 之後接 API 時，請將以下 setTimeout 區塊替換為：
    //   try {
    //     const copies = await generateCopies(selectedProduct);
    //     finish(); // API 成功後呼叫 finish()
    //     setCopyCandidates(copies);
    //     setStage('copy_ready');
    //     setTimeout(() => setShowBobaProgress(false), 1000); // 顯示完成動畫 1 秒後收起
    //   } catch (error) {
    //     reset(); // API 失敗時重置
    //     setShowBobaProgress(false);
    //     setErrorMessage('文案生成失敗，請重試');
    //     setStage('waiting_input');
    //     setTimeout(() => setErrorMessage(null), 3000);
    //   }
    // ============================================
    setTimeout(() => {
      finish(); // 觸發完成動畫
      setTimeout(() => {
        // 顯示完成動畫 1 秒後收起
        setShowBobaProgress(false);
        // 模擬 API 回傳結果
        generateCopies(selectedProduct)
          .then((copies) => {
            setCopyCandidates(copies);
            setStage('copy_ready');
          })
          .catch((error) => {
            setErrorMessage('文案生成失敗，請重試');
            setStage('waiting_input');
            setTimeout(() => setErrorMessage(null), 3000);
          });
      }, 1000);
    }, 6000);
  };

  // Handle image generation (called when user selects a copy style)
  const handleGenerateImage = async (copyId?: string) => {
    if (!uploadedImage) {
      setErrorMessage('請先上傳產品圖片');
      setTimeout(() => setErrorMessage(null), 3000);
      return;
    }
    
    const copyIdToUse = copyId || selectedCopyId;
    if (!copyIdToUse) {
      setErrorMessage('請先選擇文案風格');
      setTimeout(() => setErrorMessage(null), 3000);
      return;
    }

    // Get the latest copy text (editedText ?? content)
    const copy = copyCandidates.find(c => c.id === copyIdToUse);
    if (!copy) {
      setErrorMessage('找不到選取的文案');
      setTimeout(() => setErrorMessage(null), 3000);
      return;
    }
    
    const latestCopyText = copy.editedText ?? copy.content;
    
    // Note: In real API call, this latestCopyText should be included in the payload
    // For example: await generateImagesAPI({ image: uploadedImage, copyText: latestCopyText, template })

    setStage('image_generating');
    setGenerationStatus('queued');
    setGeneratedImages([]);
    setSelectedImage(null);

    // Simulate async generation with progress
    setTimeout(() => {
      setGenerationStatus('generating');
      setGenerationProgress(0);
      
      const progressInterval = setInterval(() => {
        setGenerationProgress(prev => {
          if (prev >= 90) {
            clearInterval(progressInterval);
            return 90;
          }
          return prev + 10;
        });
      }, 200);

      // Generate mock images using Canvas
      // In production, this would be: generateImagesAPI({ image: uploadedImage, copyText: latestCopyText })
      generateMockImages(uploadedImage)
        .then((images) => {
          clearInterval(progressInterval);
          setGenerationProgress(100);
          setGeneratedImages(images);
          setGenerationStatus('done');
          setStage('done');
          // Auto-select the first generated image
          if (images.length > 0) {
            setSelectedImage(images[0].id);
          }
        })
        .catch((error) => {
          clearInterval(progressInterval);
          setGenerationStatus('idle');
          setGenerationProgress(0);
          setStage('copy_ready');
          setErrorMessage(`圖片生成失敗: ${error instanceof Error ? error.message : '未知錯誤'}`);
          setTimeout(() => setErrorMessage(null), 3000);
        });
    }, 500);
  };

  const handleSelectImage = (imageId: string) => {
    setSelectedImage(imageId);
  };

  const handleRegenerate = () => {
    if (selectedCopyId) {
      handleGenerateImage();
    }
  };

  // Handle edit copy button click
  const handleEditCopy = (e: React.MouseEvent, copyId: string) => {
    e.stopPropagation(); // Prevent card selection when clicking edit
    const copy = copyCandidates.find(c => c.id === copyId);
    if (copy) {
      // Use editedText if exists, otherwise use original content
      const currentText = copy.editedText ?? copy.content;
      setEditingCopyId(copyId);
      setEditTextValue(currentText);
      setIsEditDialogOpen(true);
    }
  };

  // Handle save edited copy
  const handleSaveEdit = () => {
    if (!editingCopyId) return;
    
    const trimmedValue = editTextValue.trim();
    if (!trimmedValue) {
      // Don't allow saving empty text
      return;
    }

    // Update the copy candidate with edited text
    setCopyCandidates(prev => prev.map(copy => 
      copy.id === editingCopyId 
        ? { ...copy, editedText: trimmedValue }
        : copy
    ));

    // Close dialog and reset edit state
    setIsEditDialogOpen(false);
    setEditingCopyId(null);
    setEditTextValue('');
  };

  // Handle cancel edit
  const handleCancelEdit = () => {
    setIsEditDialogOpen(false);
    setEditingCopyId(null);
    setEditTextValue('');
  };

  // Handle copy style selection - triggers image generation with TeaFlow progress
  const handleSelectCopyStyle = (copyId: string) => {
    setSelectedCopyId(copyId);
    setErrorMessage(null);
    
    // 获取风格名称用于显示
    const copy = copyCandidates.find(c => c.id === copyId);
    const styleName = copy?.name || '此風格';
    setSelectedStyleName(styleName);
    
    // 清空之前的生成结果
    setGeneratedImages([]);
    setSelectedImage(null);
    
    // 显示并启动 TeaFlow 进度条
    setShowTeaFlowProgress(true);
    teaFlowStart();
    
    // 设置状态为图片生成中
    setStage('image_generating');
    setGenerationStatus('generating');
    setGenerationProgress(0);
    
    // ============================================
    // 🔄 DEMO: 模擬 API 完成（6 秒後自動完成）
    // 之後接 API 時，請將以下 setTimeout 區塊替換為：
    //   try {
    //     const images = await generateImagesAPI({ 
    //       image: uploadedImage, 
    //       copyText: copy.editedText ?? copy.content
    //     });
    //     teaFlowFinish(); // API 成功後呼叫 finish()
    //     setGeneratedImages(images);
    //     setGenerationStatus('done');
    //     setStage('done');
    //     if (images.length > 0) {
    //       setSelectedImage(images[0].id);
    //     }
    //     setTimeout(() => setShowTeaFlowProgress(false), 1200); // 顯示完成動畫 1.2 秒後收起
    //   } catch (error) {
    //     teaFlowReset(); // API 失敗時重置
    //     setShowTeaFlowProgress(false);
    //     setErrorMessage('圖片生成失敗，請重試');
    //     setStage('copy_ready');
    //     setTimeout(() => setErrorMessage(null), 3000);
    //   }
    // ============================================
    setTimeout(() => {
      teaFlowFinish(); // 觸發完成動畫
      setTimeout(() => {
        // 顯示完成動畫 1.2 秒後收起進度條並顯示結果
        setShowTeaFlowProgress(false);
        // 模擬 API 回傳結果（使用現有的 generateMockImages）
        if (uploadedImage) {
          generateMockImages(uploadedImage)
            .then((images) => {
              setGeneratedImages(images);
              setGenerationStatus('done');
              setStage('done');
              if (images.length > 0) {
                setSelectedImage(images[0].id);
              }
            })
            .catch((error) => {
              setGenerationStatus('idle');
              setStage('copy_ready');
              setErrorMessage('圖片生成失敗，請重試');
              setTimeout(() => setErrorMessage(null), 3000);
            });
        }
      }, 1200);
    }, 6000);
  };

  // Get selected copy text (use editedText if exists, otherwise use original content)
  const selectedCopyText = selectedCopyId 
    ? (() => {
        const copy = copyCandidates.find(c => c.id === selectedCopyId);
        return copy ? (copy.editedText ?? copy.content) : '';
      })()
    : '';

  // Get selected generated image URL (only from generatedImages, never fallback to uploadedImage)
  // If no image is selected but we have generated images, use the first one
  const selectedGeneratedImageUrl = selectedImage 
    ? generatedImages.find(img => img.id === selectedImage)?.url || null
    : generatedImages.length > 0 
      ? generatedImages[0].url 
      : null;

  return (
    <div className="h-full flex" style={{ backgroundColor: 'var(--df-bg)' }}>
      {/* 左側：產品資訊與文案生成 */}
      <div className="flex-1 p-6 overflow-y-auto">
        <div className="space-y-6 pr-4 max-w-4xl">
          <div>
            <h2 className="text-2xl font-semibold mb-1">內容審核中心</h2>
            <p className="text-sm text-muted-foreground">AI 多風格產出 · 人工最後審核</p>
          </div>
          
          {/* 產品資訊輸入區 */}
          <Card>
            <CardHeader>
              <CardTitle className="text-base">產品資訊輸入</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid md:grid-cols-2 gap-6">
                {/* 左欄：表單欄位堆疊 */}
                <div className="space-y-4">
                  <div className="space-y-2">
                    <Label>產品名稱</Label>
                    <Select
                      value={selectedProduct}
                      onValueChange={handleProductChange}
                      disabled={stage === 'copy_generating' || stage === 'image_generating'}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="請選擇產品" />
                      </SelectTrigger>
                      <SelectContent>
                        {products.map((product) => (
                          <SelectItem key={product} value={product}>
                            {product}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  
                  {/* Action Panel */}
                  <div className="pt-4">
                    <div className="space-y-3">
                      <div className="text-sm font-medium">行銷</div>
                      <Button
                        onClick={handleGenerateCopiesClick}
                        disabled={
                          !uploadedImage || 
                          !selectedProduct ||
                          stage === 'copy_generating' || 
                          stage === 'image_generating'
                        }
                        className="w-full"
                        style={{ backgroundColor: 'var(--df-header)', color: 'white' }}
                      >
                        {stage === 'copy_generating' ? (
                          <>
                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                            生成中…
                          </>
                        ) : (
                          <>
                            <ImageIcon className="w-4 h-4 mr-2" />
                            文案產生
                          </>
                        )}
                      </Button>
                      
                      {/* Boba Progress - 顯示在按鈕下方 */}
                      {showBobaProgress && (
                        <div className="mt-3">
                          <BobaProgress
                            progress={progress}
                            status={status}
                            showCounter={true}
                            size="md"
                          />
                        </div>
                      )}
                    </div>
                  </div>
                </div>
                
                {/* 右欄：產品照片上傳 */}
                <div className="space-y-2">
                  <ImageUploader 
                    value={uploadedImage}
                    onImageUpload={handleImageUpload}
                    onClear={handleImageClear}
                  />
                </div>
              </div>
            </CardContent>
          </Card>
          
          {/* AI 多風格產出區 */}
          <div>
            <h3 className="font-semibold mb-4">AI 多風格文案對比</h3>
            
            {errorMessage && (
              <div className="mb-3 p-2 text-sm text-destructive bg-destructive/10 border border-destructive/20 rounded">
                {errorMessage}
              </div>
            )}
            
            {stage === 'copy_generating' && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {[1, 2, 3].map((i) => (
                  <Card key={i} className="h-full">
                    <CardContent className="p-4">
                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <div className="h-4 w-20 bg-gray-200 rounded animate-pulse" />
                          <div className="h-4 w-4 bg-gray-200 rounded animate-pulse" />
                        </div>
                        <div className="space-y-2">
                          <div className="h-3 w-full bg-gray-200 rounded animate-pulse" />
                          <div className="h-3 w-full bg-gray-200 rounded animate-pulse" />
                          <div className="h-3 w-3/4 bg-gray-200 rounded animate-pulse" />
                        </div>
                        <div className="h-8 w-full bg-gray-200 rounded animate-pulse" />
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
            
            {stage === 'copy_ready' || stage === 'image_generating' || stage === 'done' ? (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-stretch">
                {copyCandidates.map((copy) => {
                  const isSelected = selectedCopyId === copy.id;
                  return (
                    <Card 
                      key={copy.id}
                      className={cn(
                        "relative transition-all h-full flex flex-col",
                        isSelected 
                          ? "ring-2 ring-primary border-primary" 
                          : "border-border hover:bg-muted/20 hover:shadow-md"
                      )}
                    >
                      <CardHeader className="pb-3">
                        <CardTitle className="text-sm flex items-center justify-between">
                          <span className="flex items-center gap-2">
                            <span className="text-lg">{copy.icon}</span>
                            {copy.name}
                          </span>
                          <Button 
                            variant="ghost" 
                            size="sm"
                            onClick={(e) => handleEditCopy(e, copy.id)}
                            className="h-6 w-6 p-0"
                            disabled={stage === 'image_generating'}
                          >
                            <Pencil className="w-3 h-3" />
                          </Button>
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="flex-1 flex flex-col">
                        <p className="text-xs whitespace-pre-line leading-relaxed text-muted-foreground flex-1">
                          {copy.editedText ?? copy.content}
                        </p>
                      </CardContent>
                      {/* Footer with Select Button */}
                      <div className="p-4 pt-0 border-t border-border mt-auto space-y-2">
                        {copy.editedText && (
                          <div className="text-xs text-muted-foreground text-center">
                            已編輯
                          </div>
                        )}
                        <Button
                          variant={isSelected ? "default" : "outline"}
                          size="sm"
                          className="w-full"
                          disabled={stage === 'image_generating'}
                          onClick={(e) => {
                            e.stopPropagation();
                            handleSelectCopyStyle(copy.id);
                          }}
                        >
                          {isSelected ? (
                            <>
                              <CheckCircle2 className="w-4 h-4 mr-2" />
                              已選擇
                            </>
                          ) : (
                            '選擇此風格'
                          )}
                        </Button>
                      </div>
                    </Card>
                  );
                })}
              </div>
            ) : stage === 'waiting_input' && (
              <div className="text-center py-8 text-sm text-muted-foreground">
                請上傳產品圖片、選擇產品名稱，然後點擊「文案產生」生成文案
              </div>
            )}
          </div>
        </div>
      </div>
      
      {/* 右側：視覺預覽 */}
      <div 
        className="flex-1 p-6 space-y-6 overflow-y-auto border-l"
        style={{ backgroundColor: 'white' }}
      >
        <div>
          <h3 className="font-semibold mb-4">圖像預覽與模擬</h3>
          
          {/* TeaFlow Progress Bar - 顯示在右上狀態區 */}
          {showTeaFlowProgress && (
            <div className="mb-4">
              <TeaFlowProgressBar
                progress={teaFlowProgress}
                status={teaFlowStatus}
                label={selectedStyleName ? `正在套用「${selectedStyleName}」...` : '正在生成圖片...'}
                showCounter={true}
                compact={true}
              />
            </div>
          )}
          
          {/* Generated Gallery - Show based on stage, never show original image */}
          <GeneratedGallery
            uploadedImage={null}
            generatedImages={generatedImages}
            selectedImage={selectedImage}
            generationStatus={generationStatus}
            generationProgress={generationProgress}
            onSelectImage={handleSelectImage}
            onRegenerate={handleRegenerate}
            stage={stage}
          />

          {/* Social Preview Tabs - Always show */}
          <div className="mt-6">
            <SocialPreviewTabs
              selectedGeneratedImage={selectedGeneratedImageUrl}
              selectedCopy={selectedCopyText}
              productName={selectedProduct}
              hasGeneratedImages={generatedImages.length > 0}
            />
          </div>
          
          {/* Action Buttons */}
          <div className="mt-6 space-y-2">
            <Button 
              className="w-full"
              style={{ backgroundColor: 'var(--df-accent)', color: 'white' }}
              disabled={!selectedImage || teaFlowStatus === 'running'}
            >
              <Send className="w-4 h-4 mr-2" />
              確認發布
            </Button>
          </div>
          
          {/* Info Panel */}
          <div className="mt-4 p-3 bg-gray-50 rounded text-xs space-y-1">
            <div className="flex justify-between">
              <span className="text-muted-foreground">產品:</span>
              <span className="font-medium">{selectedProduct || '未選擇'}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">狀態:</span>
              <Badge variant="outline" className="text-yellow-600 border-yellow-600">待審核</Badge>
            </div>
            {uploadedMeta && (
              <div className="flex justify-between">
                <span className="text-muted-foreground">圖片尺寸:</span>
                <span>{uploadedMeta.width}×{uploadedMeta.height}</span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Edit Copy Dialog */}
      <Dialog 
        open={isEditDialogOpen} 
        onOpenChange={(open) => {
          if (!open) {
            // When dialog closes (by any means), reset edit state
            handleCancelEdit();
          } else {
            setIsEditDialogOpen(true);
          }
        }}
      >
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle>編輯文案</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="edit-textarea">文案內容</Label>
              <Textarea
                id="edit-textarea"
                value={editTextValue}
                onChange={(e) => setEditTextValue(e.target.value)}
                placeholder="請輸入文案內容"
                className="min-h-[200px]"
                rows={8}
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={handleCancelEdit}
            >
              取消
            </Button>
            <Button
              onClick={handleSaveEdit}
              disabled={!editTextValue.trim()}
            >
              儲存
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
